M48
; DRILL file {KiCad (6.0.0)} date Sun Feb  5 23:32:15 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-05T23:32:15-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1693
%
G90
G05
T1
X0.1929Y-2.3677
X0.8071Y-2.3677
T2
X0.5Y-2.3677
T3
X0.2362Y-0.6299
X0.2362Y-3.2677
X2.8346Y-0.6299
X2.8346Y-3.2677
T0
M30
